# Generated by Django 4.1.6 on 2023-02-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_registro_btotalegresos_registro_btotalingresos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='btotalegresos',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='btotalingresos',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='etotalegresos',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='etotalingresos',
        ),
    ]
